language: node_js
node_js:
- '0.10'
rvm:
- 2.1.0
before_install:
- gem install compass

script: node ./node_modules/grunt-cli/bin/grunt --target=prod

after_script: cat ./stylesheets/youtube-dark.css
