language: node_js
node_js:
- '0.10'
rvm:
- 2.1.0
before_install:
- npm install -g grunt-cli
- gem install compass

install: npm install

script: grunt --target=prod

after_script: cat ./stylesheets/youtube-dark.css
